force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAN-{0000}</displayFormat>
        <label>Candidate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidate__c/VacancyCandidate__c.object-meta.xml
<CustomObject>
    <label>Vacancy Candidate</label>
    <nameField>
        <displayFormat>VC-{00000}</displayFormat>
        <label>Vacancy Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacancy Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VacancyCandidate__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Vacancies</relationshipLabel>
    <relationshipName>Vacancy_Pivot</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VacancyCandidate__c/fields/UniqueID__c.field-meta.xml
<CustomField>
    <fullName>UniqueID__c</fullName>
    <externalId>true</externalId>
    <label>UniqueID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VacancyCandidate__c/fields/Vacancy__c.field-meta.xml
<CustomField>
    <fullName>Vacancy__c</fullName>
    <label>Vacancy</label>
    <referenceTo>Vacancy__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidate_Pivot</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecruitingController.cls
/**
 * Created by kkukh on 9/10/2019.
 */

public with sharing class RecruitingController {
  @AuraEnabled
  public static void submitVacanciesCandidates(String vacCanMapJson) {
    Map<String, List<String>> vacCanMap = (Map<String, List<String>>) JSON.deserialize(
      vacCanMapJson,
      Map<String, List<String>>.class
    );

    Set<String> vacanciesId = vacCanMap.keySet();
    List<VacancyCandidate__c> vacCanList = new List<VacancyCandidate__c>();

    for (String vacancyId : vacanciesId) {
      vacCanList.addAll(
        createJunctionRecords(vacancyId, vacCanMap.get(vacancyId))
      );
    }

    upsert vacCanList UniqueID__c;

    submitForApproval(vacCanList);
    transferVacanciesToManager(vacanciesId);
  }

  public static List<VacancyCandidate__c> createJunctionRecords(
    String vacancyId,
    List<String> candidatesId
  ) {
    List<VacancyCandidate__c> vacCanList = new List<VacancyCandidate__c>();

    for (String candidateId : candidatesId) {
      vacCanList.add(
        new VacancyCandidate__c(
          Vacancy__c = vacancyId,
          Candidate__c = candidateId,
          UniqueID__c = (vacancyId + candidateId)
        )
      );
    }

    return vacCanList;
  }

  public static void submitForApproval(VacancyCandidate__c[] vacCanList) {
    Map<Id, VacancyCandidate__c> vacCanOwnerMap = new Map<Id, VacancyCandidate__c>(
      [
        SELECT Id, Vacancy__r.VacancyOwner__c
        FROM VacancyCandidate__c
        WHERE Id IN :vacCanList
      ]
    );

    for (VacancyCandidate__c vacCan : vacCanList) {
      Approval.ProcessSubmitRequest vacCanApproveReq = new Approval.ProcessSubmitRequest();

      vacCanApproveReq.setObjectId(vacCan.Id);
      vacCanApproveReq.setSubmitterId(UserInfo.getUserId());
      vacCanApproveReq.setSkipEntryCriteria(true);
      vacCanApproveReq.setNextApproverIds(
        new List<Id>{ vacCanOwnerMap.get(vacCan.Id).Vacancy__r.VacancyOwner__c }
      );
      vacCanApproveReq.setProcessDefinitionNameOrId(
        'Approve_Multiple_Candidates'
      );

      Approval.ProcessResult vacCanApproveRes = Approval.process(
        vacCanApproveReq
      );
    }
  }

  public static void transferVacanciesToManager(Set<String> vacanciesId) {
    List<Vacancy__c> vacanciesList = [
      SELECT Id, OwnerId, VacancyOwner__c
      FROM Vacancy__c
      WHERE Id IN :vacanciesId
    ];

    for (Vacancy__c vacancy : vacanciesList) {
      vacancy.SubmitedByRecruiter__c = true;
      vacancy.OwnerId = vacancy.VacancyOwner__c;
    }

    update vacanciesList;
  }
}